### ISSUE TITLE
Kubernetes Ingress entities

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-agent-core#3]
Kubernetes Ingress resources should be added as ZMON entities. The exact structure needs to be discussed as the Ingress resource can have host and path rules.

**Comment by harti2006** [comment]
It would also be nice to include the exact key that can be used to obtain Skipper metrics for a particular ingress, e.g. "my-app_example_com" to be able to filter Skipper metrics results for keys like "skipper.servehost.my-app_example_com.*".

**Comment by mikkeloscar** [comment]
@harti2006 assuming the ingress entity includes the hostname, then I think it's reasonable to do the hostname -> skipper metric transformation in the ZMON check.

Putting it directly in zmon-agent seems a bit too specific to me.

**Comment by hjacobs** [comment]
Maybe somebody :tm: can tackle this "soon" @mohabusama ?
