### ISSUE TITLE
ZMON should detect old pod entities and clean them up.

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-zmon/zmon-agent-core#5]
We often see ZMON running checks on old pods which have been deleted for several hours.

It seems like the agent doesn't clean up the old entities as it should.

For now we can work around the problem by clicking "cleanup" in the ZMON UI, but it's a bit inconvenient :)

**Comment by Jan-M** [comment]
I believe the issue is "misstated", checks are not getting executed thus the entity becomes blue (no new result recently). This is a scheduler/ui issue that cleanup does not happen.
