### ISSUE TITLE
Add kube_pvc entities.

### ISSUE THREAD

**Issue by mikkeloscar** [zalando-zmon/zmon-agent-core#73]
Users want to monitor the disk usage of the [PVCs](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims) they provision. Therefore it would be very handy to have a `kube_pvc` entity which can collect this information making it simple to create checks/alerts per PVC.

PVCs by themselves does not have any information about the actually backing EBS volume, this is only available in the corresponding Persistent Volume that the claim owns. Therefore it would be convenient to have the volumeid also exposed in the `kube_pvc` entity because then you can get cloudwatch metrics for the EBS volume and you can filter on your pvc name which is human readable rather than the PV name which is a uuid.

**Comment by mohabusama** [comment]
@mikkeloscar So ``kube_pvc`` should include info from the ``pvc`` and corresponding ``pv`` resources? but no need to separate them as ``kube_pv`` and ``kube_pvc``?

**Comment by mikkeloscar** [comment]
The thing is I don't think `kube_pv` would be super useful by itself, because it's always created from a PVC. We could have both `kube_pv` and `kube_pvc` but then we would have to do the lookup of volume id in the check rather than get it by default in the entity.

What you really want as a user is to get volume stats based on the human readable name that you defined for the PVC IMO.

**Comment by mohabusama** [comment]
I will go with ``kube_pvc`` for now then.

**Comment by mikkeloscar** [comment]
Done in #74
