### ISSUE TITLE
Add namespace also to postgresql_database entities

### ISSUE THREAD

**Issue by ePaul** [zalando-zmon/zmon-agent-core#82]
The `postgresql_cluster` entities have a "namespace" field, which allows filtering the databases one wants to look at. It would be nice if the same field is also available in the `postgresql_database` field.

As I understand, each database is in exactly one cluster, which has a namespace, so there should be no problem of populating this field too.

**Comment by laceyallyn** [comment]
@ePaul could you help us understand why this would be helpful?

**Comment by ePaul** [comment]
@laceyallyn Sorry, I missed your question.

This would be useful when setting up a generic check/alert for a team. All resources owned by our team are inside the same namespace, so filtering by namespace avoids having to set up a separate alert for each DB, or to adjust the filtering criteria for an existing one whenever creating a new database.
